name: Build and Deploy

on:
  push:
    branches: [develop]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase owner
        run: echo "OWNER_LOWER=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./src/CryptoArbitrage.API
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/crypto-arbitrage/api:latest
            ghcr.io/${{ env.OWNER_LOWER }}/crypto-arbitrage/api:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./client
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/crypto-arbitrage/web:latest
            ghcr.io/${{ env.OWNER_LOWER }}/crypto-arbitrage/web:${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    if: success()

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY_BASE64 }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.DEPLOY_HOST }} >> ~/.ssh/known_hosts 2>/dev/null

      - name: Deploy to DigitalOcean
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_SHA: ${{ github.sha }}
          PROD_POSTGRES_PASSWORD: ${{ secrets.PROD_POSTGRES_PASSWORD }}
          PROD_JWT_SECRET: ${{ secrets.PROD_JWT_SECRET }}
          PROD_ENCRYPTION_KEY: ${{ secrets.PROD_ENCRYPTION_KEY }}
          PROD_GOOGLE_CLIENT_ID: ${{ secrets.PROD_GOOGLE_CLIENT_ID }}
          PROD_GOOGLE_CLIENT_SECRET: ${{ secrets.PROD_GOOGLE_CLIENT_SECRET }}
          PROD_DOMAIN: ${{ secrets.PROD_DOMAIN }}
        run: |
          # Copy deploy script to droplet
          scp -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no ./deploy.sh $DEPLOY_USER@$DEPLOY_HOST:/tmp/deploy.sh

          # Execute deploy script
          ssh -i ~/.ssh/deploy_key $DEPLOY_USER@$DEPLOY_HOST \
            GITHUB_REPOSITORY="$GITHUB_REPOSITORY" \
            GITHUB_SERVER_URL="$GITHUB_SERVER_URL" \
            GITHUB_SHA="$GITHUB_SHA" \
            PROD_POSTGRES_PASSWORD="$PROD_POSTGRES_PASSWORD" \
            PROD_JWT_SECRET="$PROD_JWT_SECRET" \
            PROD_ENCRYPTION_KEY="$PROD_ENCRYPTION_KEY" \
            PROD_GOOGLE_CLIENT_ID="$PROD_GOOGLE_CLIENT_ID" \
            PROD_GOOGLE_CLIENT_SECRET="$PROD_GOOGLE_CLIENT_SECRET" \
            bash /tmp/deploy.sh "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"

          rm ~/.ssh/deploy_key
